server:
  port: 9090

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.213.128:3306/fileupload?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis??
mybatis:
  # ???????
  type-aliases-package: cn.lyz.**.domain
  # ??mapper?????????mapper.xml????
  mapper-locations: classpath:mapper/*.xml
  # ?????????
  config-location: classpath:mybatis/mybatis-config.xml
